config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  get '/blogs', to: 'blogs#index' #追記する
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  # 追記する。render :new が省略されている。
  def new
      # 追記する
    @blog = Blog.new
  end
  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        # Blog.create(blog_params)
        # Blog.create(params.require(:blog).permit(:title, :content))
        redirect_to blogs_path, notice: "ブログを作成しました！"
        # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
        # redirect_to new_blog_path
        # # redirect_to "/blogs/new"のこと
      else
        # 入力フォームを再描画します。
        # 処理終了後に呼び出されるビューがnew.html.erbに変更される
        render :new
      end
    end
  end
  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end
  def show
    # @blog = Blog.find(params[:id])
  end
  def edit
  # @blog = Blog.find(params[:id])
  end
  def update
    # @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
  # idをキーとして値を取得するメソッドを追加
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを更新する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bootstrap
      </a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
    </div>
  </div>
</nav><
h1>ブログ一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to 'DIVE INTO CODEのページへ', 'https://diveintocode.jp/'  %>
<%= link_to 'ブログ一覧画面に戻る', blogs_path %>
<%= link_to 'ブログ新規作成画面に移動する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<br>
<%= link_to 'ブログ一覧画面に戻る', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <ul>
      <li><a href="#">Bootstrapテキストページ</a></li>
      <li><a href="#">トップページ</a></li>
    </ul>
  </header>
  <%= yield %>
  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 DIVE INTO CODE Corp.</p>
  </footer>
</body>
</html>

app/views/tops/index.html.erb
<div class="container">
  <h1 class="title">Bootstrap
    <span class="label label-success">challenge!</span>
  </h1>
  <div class="alert alert-success">alertクラス</div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bootstrap</a>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="">top</a></li>
          <li><a href="">menu1</a></li>
          <li><a href="">menu2</a></li>
        </ul>
      </div>
    </div>
  </nav>
    <!-- <nav class="menu">
      <ul class="row">
        <li class="col-md-4">top</li>
        <li class="col-md-4">menu1</li>
        <li class="col-md-4">menu2</li>
      </ul>
    </nav> -->
  <article class="row">
    <div class="contents col-md-6">
      <ul class="row">
      <li class="col-sm-6 col-md-3">contents1</li>
      <li class="col-sm-6 col-md-offset-1 col-md-8">contents2</li>
      <li class="col-sm-6 col-md-5">contents3</li>
      <li class="col-sm-6 col-md-offset-2 col-md-5">contents4</li>
      </ul>
    </div>
    <div class="topic col-md-6">
      <ul>
        <li>bootstrapを使ってレスポンシブデザインを実現しよう！</li>
        <li>やればできる！bootstrapを使ってみよう！</li>
        <li>怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に！</li>
      </ul>
    </div>
  </article>
</div>